### PR TITLE
mongo db name from variable MONGO_DB

### PR DESCRIPTION
**Pull request by scream4ik**

### CODE REVIEW

**Comment by rodorgas** [comment]
That is nice, thanks! Could you update the README? Now we need to specify the database on MONGO_DB.

**Comment by rodorgas** [comment]
Actually I'm using another version on production that manages authentication via RocketChat API, since this method manipulating MongoDB directly doesn't seem to work on latest RocketChat versions. I think we have to touch other mongo schemas, but it's undocumented.

Could you confirm if this app is broken or not on latest RocketChat instance? Or do you use an older version?

**Comment by scream4ik** [comment]
I'm using latest version RocketChat on heroku.
Example of MONGO_DB for heroku
```
MONGO_DB = '<dbuser>:<dbpassword>@<dbhost>:<dbport>/<dbname>?authSource=<dbname>'
```
Example for localhost
```
MONGO_DB = 'localhost/rocketchat'
```

**Comment by scream4ik** [comment]
Could you update the README about ROCKETCHAT_AUTH_TOKEN and ROCKETCHAT_USER_ID variables?

**Comment by rodorgas** [comment]
Sure, will update README but first need to release this version (1.3). Issues I need to address are:

- Django Clickjacking middleware doesn't allow the website to be loaded in RocketChat IFrame. People can disable this middleware but it's bad for security.

- RocketChat auth token expires every 3 months [accordingly this issue](https://github.com/RocketChat/Rocket.Chat/issues/2894). Auth token will need to be manually updated when it expires, what is not reasonable

**Pull request merged**
